### ISSUE TITLE
loggly-python-handler breaks application startup in Django

### ISSUE THREAD

**Issue by maciejstromich** [loggly/loggly-python-handler#6]
since 0.9.8 requests-futures was informing users about background_callback deprecation in favour of hooks and with version 1.0.0 released 14 days ago it's not possible to use loggly-python-handler without manually pinning requests-futures to version prior 1.0.0.

**Comment by bruzina** [comment]
Closing this one as `background_callback` is removed from the `master `and it is released at [PyPI](https://pypi.org/project/loggly-python-handler/)
